from bj import *
hand1=Hand(1,0,0)
deck=generate_deck()
hand1.deal()
print(hand1.cards_in_hand[0].get_sign())
print(hand1.cards_in_hand[1].get_sign())
print(hand1.first_value)
print(hand1.second_value)
hand1.hit()
print(hand1.cards_in_hand[0].get_sign())
print(hand1.cards_in_hand[1].get_sign())
print(hand1.cards_in_hand[2].get_sign())
print(hand1.first_value)
print(hand1.second_value)